viewer/basic_app/urls.py
from django.urls import path,re_path
from . import views

app_name="basic_app"

urlpatterns=[
    path('searchbar/',views.searchbar,name='searchbar'),
    re_path(r'^faculties$',views.FacultyListView.as_view(),name="list"),
    re_path(r'^(?P<pk>\d+)/$',views.FacultyDetailView.as_view(),name='detail'),
    re_path(r'^create/$',views.FacultyCreateView.as_view(),name='create'),
    re_path(r'^update/(?P<pk>\d+)/$',views.FacultyUpdateView.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.FacultyDeleteView.as_view(),name='delete'),
]

viewer/viewer/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include

urlpatterns = [
    re_path(r'^basic_app/',include(('basic_app.urls','basic_app'),namespace='basic_app')),
    re_path(r'^admin/', admin.site.urls),
]

viewer/basic_app/models.py
from django.db import models
from django.urls import reverse
import datetime
# Create your models here.
class Faculty(models.Model):
    name=models.CharField(max_length=256)
    age=models.PositiveIntegerField()
    designation=models.CharField(max_length=50)
    faculty_id=models.CharField(max_length=5,blank=True)

    photo = models.ImageField(upload_to='photos',default='default_pic.jpg')

    MALE="male"
    FEMALE="female"

    GENDER_CHOICE=[
    (MALE,"male"),
    (FEMALE,"female")
    ]

    gender=models.CharField(
        max_length=10,
        choices=GENDER_CHOICE,
        default=MALE
    )

    dob=models.DateField(default=datetime.date.today)

    groups=[
    ("A+ve","A+ve"),
    ("B+ve","B+ve"),
    ("A-ve","A-ve"),
    ("B-ve","B-ve"),
    ("O+ve","O+ve"),
    ("AB-ve","A-ve")
    ]

    blood_group=models.CharField(
        max_length=5,
        choices=groups,
        blank=True
    )


    aadhar_no=models.CharField(max_length=12)
    pan_no=models.CharField(max_length=10,blank=True)
    mobile=models.CharField(max_length=10,blank=True)
    email=models.EmailField(blank=True)


    state_choices = [
        ("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),
        ("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),
        ("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),
        ("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),
        ("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),
        ("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),
        ("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),
        ("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry")
        ]
    state=models.CharField(
    max_length=35,
    choices=state_choices,
    blank=True
    )
    district=models.CharField(max_length=256,blank=True)
    house_no=models.PositiveIntegerField(default=0)
    locality=models.CharField(blank=True,max_length=100)
    pin=models.CharField(max_length=6,blank=True)
    permanentAddressSameAsCurrentAddress=models.BooleanField(default=True)


    qualification_choices=[
    ("SSC","SSC"),
    ("Inter","Inter"),
    ("UG","UG"),
    ("PG","PG"),
    ("Phd","Phd"),
    ("Others","Others")
    ]
    qualification=models.CharField(
    max_length=25,
    choices=qualification_choices,
    blank=True
    )
    college=models.CharField(max_length=100,blank=True)
    graduation_year=models.CharField(max_length=4,blank=True)
    university=models.CharField(max_length=60,blank=True)
    percentage=models.DecimalField(decimal_places=2,max_digits=5,default=0.00)

    award=models.CharField(max_length=100,blank=True)
    year_award=models.CharField(max_length=4,blank=True)
    org_award=models.CharField(max_length=50,blank=True)

    #journals
    journal_name=models.CharField(max_length=100,blank=True)
    journal_vol=models.PositiveIntegerField(default=1)
    issn_no=models.PositiveIntegerField(default=0)
    publisher=models.CharField(max_length=100,blank=True)
    year_of_publication=models.CharField(max_length=4,blank=True)
    article_title=models.CharField(max_length=50,blank=True)




    #r&d
    project_title=models.CharField(max_length=100,blank=True)
    duration=models.PositiveIntegerField(default=1)
    cost_of_project=models.DecimalField(decimal_places=5,max_digits=10,default=0.00)
    funding_agency=models.CharField(max_length=100,blank=True)
    start_date=models.DateField(default=datetime.date.today)
    end_date=models.DateField(default=datetime.date.today)



    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk' :self.pk})

    def __str__(self):
        return self.name

viewer/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models

from django.urls import reverse_lazy
# Create your views here.

class FacultyListView(ListView):
    model=models.Faculty

class FacultyDetailView(DetailView):
    model=models.Faculty
    template_name='basic_app/faculty.html'

class FacultyCreateView(CreateView):
    fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
    'pan_no','mobile','email','state','district','pin','permanentAddressSameAsCurrentAddress',
    'qualification','college','university','percentage','award','year_award','org_award',
    'journal_name','journal_vol','issn_no','publisher','year_of_publication','article_title',
    'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
    )
    model=models.Faculty

class FacultyUpdateView(UpdateView):
    fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
    'pan_no','mobile','email','state','district','pin','permanentAddressSameAsCurrentAddress',
    'qualification','college','university','percentage','award','year_award','org_award',
    'journal_name','journal_vol','issn_no','publisher','year_of_publication','article_title',
    'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
    )
    model=models.Faculty

class FacultyDeleteView(DeleteView):
    model=models.Faculty
    success_url=reverse_lazy('basic_app:list')



def searchbar(request):
    if request.method=='GET':
        search=request.GET.get('search')
        facs=models.Faculty.objects.all().filter(faculty_id=search)

        return render(request,'basic_app/searchbar.html',{'facs':facs})

viewer/basic_app/templates/basic_app/faculty.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <h1>Welcome to the details page!</h1>
    <h2>Faculty details:</h2>
    <h3>Personal Details:</h3>
    <p>{{faculty.name}}</p>
    <p>{{faculty.age}}</p>
    <p>{{faculty.designation}}</p>
    <p>{{faculty.gender}}</p>
    <p>{{faculty.dob}}</p>
    <br>
    <h3>Important details:</h3>
    <p>{{faculty.faculty_id}}</p>
    <p>{{faculty.aadhar_no}}</p>
    <p>{{faculty.pan_no}}</p>
    <p>{{faculty.email}}</p>
    <p>{{faculty.university}}</p>
    <p>{{faculty.percentage}}</p>


    <a href="{% url 'basic_app:list' %}">Go back to list</a>
    <br>
    <a href="{% url 'basic_app:update' pk=faculty.pk%}">Update</a>
    <br>
    <a href="{% url 'basic_app:delete' pk=faculty.pk%}">Delete</a>
  </body>
</html>


<!--fields=('name','age','designation','gender','dob','faculty_id','blood_group','aadhar_no',
  'pan_no','mobile','email','state','district','pin','permanentAddressSameAsCurrentAddress',
  'qualification','college','university','percentage','award','year_award','org_award',
  'journal_name','journal_vol','issn_no','publisher','year_of_publication','article_title',
  'project_title','duration','cost_of_project','funding_agency','start_date','end_date'
  )--!>

viewer/basic_app/templates/basic_app/faculty_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <h1>Delete {{school.name}}??</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
      <a href="{% url 'basic_app:detail' pk=faculty.pk %}">Cancel</a>

    </form>
  </body>
</html>

viewer/basic_app/templates/basic_app/faculty_form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <center>
  <body>
    <h1>
      {% if not form.instance.pk %}
      Create School
      {% else %}
      Update School
      {% endif %}
    </h1>

    <form  method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="" value="submit">
    </form>
  </body>
</center>
</html>

viewer/basic_app/templates/basic_app/faculty_list.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body >
    <form action="{% url 'basic_app:searchbar' %}" method="get">
        {% csrf_token %}
        <input type="text" name="search">
        <button type="submit" name="submit">Search</button>
      </form>


    <h1>Here's a list of the faculty!</h1>
    <ol>
      {% for faculty in faculty_list %}
      <h2><li><a href="{{faculty.id}}">{{faculty.name}}</a></li></h2>
      {% endfor %}
    </ol>
    <a href="{% url 'basic_app:create' %}">Add New Faculty</a>
  </body>
</html>

<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="home.css">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light" id="navparent">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Faculty Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="search1">
              <button class="btn btn-outline-success" type="submit" id="search2">Search</button>
            </form>
          </div>
        </div>
      </nav>

</body>
</html>
--!>

viewer/basic_app/templates/basic_app/hello.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello World!</h1>
    <h1>My name is {{name}}</h1>
  </body>
</html>

viewer/basic_app/templates/basic_app/searchbar.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body style="text-align:center">

    {% if facs %}
    <h1>Results Found!</h1>
    <br>
    <ol>
      {% for i in facs%}
      <li><h2><a href="/basic_app/{{i.id}}">{{i.name}}</a></h2></li>
      {% endfor %}
    </ol>

    {% else %}
    <h2>No results!</h2>
    <a href="/basic_app/faculties/">Go back to list</a>

    {% endif %}

  </body>
</html>